import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@arraypress/waveform-player/dist/waveform-player.css";
import GlobalNav from "@/components/GlobalNav";
import PlayTracker from "@/components/PlayTracker";
import StreakWidget from "@/components/StreakWidget";
import type { Metadata, Viewport } from "next";
import PWARegister from "@/components/PWARegister";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Epsilone",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      {
        url: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    apple: "/icons/apple-touch-icon.png",
  },
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#000000",
  colorScheme: "dark",
};
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalNav />
        {children}
        <PlayTracker />
        <StreakWidget />
        <PWARegister />
      </body>
    </html>
  );
}
